version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - /docker/etc/letsencrypt/live/waspscripts.com/cert.pem:/etc/letsencrypt/live/waspscripts.com/cert.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/fullchain.pem:/etc/letsencrypt/live/waspscripts.com/fullchain.pem
      - /docker/etc/letsencrypt/live/waspscripts.com/privkey.pem:/etc/letsencrypt/live/waspscripts.com/privkey.pem
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - hive

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - /docker/etc/letsencrypt/live/waspscripts.com:/cert
    networks:
      - hive

  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare:latest
    command: renew --dns-cloudflare
    volumes:
      - /docker/etc/letsencrypt:/etc/letsencrypt
      - /docker/var/lib/letsencrypt:/var/lib/letsencrypt
      - /docker/data/letsencrypt:/data/letsencrypt
      - /docker/var/log/letsencrypt:/var/log/letsencrypt

  certbot-restarter:
    container_name: certbot-restarter
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - /bin/sh
      - -c
      - while true; do sleep 86400; docker restart certbot; done
    restart: unless-stopped

networks:
  hive:
    external: true
